# Funding options for the Venice AI SDK
# Uncomment and configure if you set up sponsorship

# github: [your-username]
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username
# custom: ["https://your-donation-link.com"]
