/**
 * Types for Venice.ai Embeddings API
 */

/**
 * Request to create embeddings
 */
export interface CreateEmbeddingRequest {
  /**
   * Input text to embed, encoded as a string or array of strings.
   * To embed multiple inputs in a single request, pass an array of strings.
   */
  input: string | string[];

  /**
   * ID of the model to use.
   * @default "text-embedding-bge-m3"
   */
  model?: string;

  /**
   * The format to return the embeddings in.
   * Can be either float or base64.
   * @default "float"
   */
  encoding_format?: 'float' | 'base64';

  /**
   * The number of dimensions the resulting output embeddings should have.
   * Only supported in some models.
   */
  dimensions?: number;

  /**
   * A unique identifier representing your end-user, which can help Venice
   * monitor and detect abuse.
   */
  user?: string;
}

/**
 * Single embedding object
 */
export interface Embedding {
  /**
   * The object type, which is always "embedding"
   */
  object: 'embedding';

  /**
   * The embedding vector, which is a list of floats
   */
  embedding: number[];

  /**
   * The index of the embedding in the list of embeddings
   */
  index: number;
}

/**
 * Token usage information
 */
export interface EmbeddingUsage {
  /**
   * The number of tokens used by the prompt
   */
  prompt_tokens: number;

  /**
   * The total number of tokens used by the request
   */
  total_tokens: number;
}

/**
 * Response from creating embeddings
 */
export interface CreateEmbeddingResponse {
  /**
   * The object type, which is always "list"
   */
  object: 'list';

  /**
   * The list of embeddings generated by the model
   */
  data: Embedding[];

  /**
   * The name of the model used to generate the embedding
   */
  model: string;

  /**
   * The usage information for the request
   */
  usage: EmbeddingUsage;
}

/**
 * Available embedding models
 */
export const EMBEDDING_MODELS = {
  BGE_M3: 'text-embedding-bge-m3',
} as const;

export type EmbeddingModel = typeof EMBEDDING_MODELS[keyof typeof EMBEDDING_MODELS];
